apiVersion: v1
kind: Service
metadata:
  name: self-healing-service
  namespace: default
spec:
  selector:
    app: self-healing-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30080
